[package]
name = "my_mpi"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "my_mpi"
path = "src/main.rs"

[profile.dev]
opt-level=3

[lib]
name = "mpi"
path = "src/mpi/lib.rs"
crate-type = ["rlib", "cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
criterion = {path = "deps/criterion", features = ["html_reports"]}

[[bench]]
name = "mem_benchmark"
harness = false

[dependencies]
libc = "0.2"
zstr = "0.1.1"