on:
  push:
    branches:
      - master
  
name: tests

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - 1.64

    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive
        name: Checkout submodules

      - uses: actions-rs/toolchain@v1
        name: Setup rust toolchain
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        name: Build release
        with:
          command: build
          args: --release

      - uses: actions-rs/cargo@v1
        name: Build with minimal features
        with:
          command: build

      - uses: actions-rs/cargo@v1
        name: Test with minimal features
        with:
          command: test

      - uses: actions-rs/cargo@v1
        name: Check for non-standard formatting
        if: ${{ matrix.rust == 'stable' }}
        with:
          command: fmt
          args: --all -- --check

#      - uses: actions-rs/cargo@v1
#        name: Check for clippy hints
#        with:
#          command: clippy
#          args: -- -D warnings